### PR TITLE
Feature/split enabled to edit review and public review

### PR DESCRIPTION
**Pull request by oszedev**
Split the addon is enabled in to two settings. One for the public preview and one for the rest. This to enabled the option to only use external page preview.

### CODE REVIEW

**Comment by barteksekula** [comment]
@oszedev Not sure if I understood the PR correctly but isn't it the same to set EditableLinksEnabled to false? https://github.com/advanced-cms/advanced-reviews#options-1

**Comment by oszedev** [comment]
From what I can tell EditableLinksEnabled = false does not disable the the functionality for adding comments to the page version. 
It will still add the button for turning reviews on and off.
This use case was to only allow creating external review links and nothing else.

**Comment by barteksekula** [comment]
@oszedev thank you for your contribution. Your fix is now part of https://nuget.optimizely.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.9.1 (net4framework) and https://nuget.optimizely.com/package/?id=Advanced.CMS.AdvancedReviews&v=1.0.0 (net5core)

**Comment by barteksekula** [comment]
https://github.com/advanced-cms/advanced-reviews#options-1
I renamed the option a bit and now in order to turn off the command you just need to set IsReviewCommentsCommandEnabled to false.

**Pull request merged**
